### ISSUE TITLE
exit_with_link 5 'ERROR: Unknown status or phase encountered'

### ISSUE THREAD

**Issue by jesusmah** [Osthanes/update_service#54] opened 2017-04-14 13:08 UTC
Hi,

I am getting the following error:
exit_with_link 5 'ERROR: Unknown status or phase encountered'
all of the sudden when I execute my pipelines with AD integrated in there. It happens during the AD Begin job. These pipelines were working fine and all of the sudden I am getting those errors.
Could you please help me out?

Thank you very much in advance.

PS: I am attaching the complete log file of the pipeline execution.
[pipeline_log.txt](https://github.com/Osthanes/update_service/files/922090/pipeline_log.txt)

**Comment by ghost** [comment] 2017-04-18 18:48
I'm having the same problem here, any thoughts?

**Comment by jayagl** [comment] 2017-04-26 01:09
+1

**Comment by sousa-cit** [comment] 2017-04-26 11:44
+1
Same issue here.

**Comment by ptaube** [comment] 2017-04-27 14:42
I was able to reproduce the issue. Debugging the code right now

**Comment by ptaube** [comment] 2017-04-28 07:06
There is a fix available in the staging repo https://github.com/IBMActiveDeploy-Toolchain/update_service 

In order to use the staging repos instead of the Osthanes production repo please execute following steps:

1) Open the deploy stage in your pipeline and in configure stage execute:
2) Create an environment variable called GIT_HOME and set it to IBMActiveDeploy-Toolchain
3) Create an environment variable called LOG_LEVEL and set it to 4
4) Open the Active Deploy Start job and change the name of the repository used from Osthanes to IBMActiveDeploy-Toolchain (See below)
5) Open the Active Deploy Complete job and change the name of the repository used from Osthanes to IBMActiveDeploy-Toolchain (See below)
6) Start the toolchain and verify the fix

Change for ActiveDeploy Start:

source ${EXT_DIR}/git_util.sh
git_retry clone https://github.com/IBMActiveDeploy-Toolchain/update_service.git activedeploy
activedeploy/activedeploy_step_1.sh

Change for ActiveDeploy Complete:

source ${EXT_DIR}/git_util.sh
git_retry clone https://github.com/IBMActiveDeploy-Toolchain/update_service.git activedeploy
activedeploy/activedeploy_step_2.sh

Please test the fix and let me know your test results.

**Comment by jayagl** [comment] 2017-05-02 02:10
Worked well until it reached the complete phase - 
```
Preparing to start the job...
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 110
failed
```

EDIT: That was just a one off occurrence. Seems to be working fine now

**Comment by ptaube** [comment] 2017-05-03 07:40
I just merged the fix into the production repository Osthanes

**Closed as completed by ptaube** 2017-05-03 07:40 UTC

**Comment by jesusmah** [comment] 2017-05-03 09:17
@ptaube sorry I was on holiday and did not see this. I have just tested the delivery pipelines + AD integration and did work fine for me. Thanks
