### ISSUE TITLE
Unknown Status error after upgrade to Toolchain

### ISSUE THREAD

**Issue by jayagl** [Osthanes/update_service#55] opened 2017-04-26 01:56 UTC
Not sure if it is related to #54 but I am facing a similar but slightly different error after "upgrading" to IBM Bluemix DevOps Toolchain from the Jazz hub project pipeline. 

It happens in the begin step after deploying a temp version of the app. It issues a `active-deploy-create` command successfully and starts the process but then fails to recognise `in_progress` as valid status and throws an `Unknown Status` error.

For more info on things I've tried to fix the issue refer to [the SO question I created](http://stackoverflow.com/questions/43578815/active-deploy-begin-step-fails-after-upgrade-to-devops-toolchain).

Find below the full log from the Pipeline step for Active Deploy begin (edited for privacy):
``` 
Target: https://api.ng.bluemix.net
git clone https://github.com/Osthanes/activedeploy_common.git common ...
git clone https://github.com/Osthanes/activedeploy_common.git common
Cloning into 'common'...
Init runtime of 1m 1s
git clone https://github.com/Osthanes/update_service.git activedeploy
Cloning into 'activedeploy'...
--- INFO: Update gui url is: https://activedeploy.ng.bluemix.net
--- INFO: Not initial version
--- INFO: ROUTE_DOMAIN is: mybluemix.net
--- INFO: check if AD instance exists with cf services, if not create it.
--- INFO: Found Active Deploy Instance: activedeploy-for-pipeline
--- INFO: Beginning update with cf active-deploy-create ...
--- INFO: Calling cf active-deploy-create my-app_8 my-app_12 --manual --quiet --timeout 60s --rampup 5m --rampdown 5m --test 1s --algorithm rorb
--- INFO: Initiated update: 6ce3d626-78e7-46c8-8e32-4131c825c888
Performing active-deploy-show command in org ISW / space my-space as my_email@email.com...
Showing status for deployment 6ce3d626-78e7-46c8-8e32-4131c825c888 / space 66ab12ee-1b83-4cb9-a21d-cdb3604888a9...
OK

label: my-app_8-to-my-app_12
space: my-space
routes: my-app.mybluemix.net
phase: rampup
start group: my-app_8 app (1)
successor group: my-app_12 app (1)
algorithm: rorb
deployment id: 6ce3d626-78e7-46c8-8e32-4131c825c888
transition type: manual
rampup duration: 1% of 5m
test duration: 1s
rampdown duration: 5m
status: in_progress
status messages: <none>
--- INFO: AD service Instance exists. AD service name is: activedeploy-for-pipeline
--- INFO: AD service GUID is: d615a7e6-7323-46bd-9e55-d627b2909098
**********************************************************************
Deployment URL
https://new-console.ng.bluemix.net/services/d615a7e6-7323-46bd-9e55-d627b2909098?ace_config={%22spaceGuid%22:%2266ab12ee-1b83-4cb9-a21d-cdb3604888a9%22}
**********************************************************************
--- ERROR: Unknown status: 
--- ERROR: label: my-app_8-to-my-app_12 space: my-space routes: my-app.mybluemix.net phase: rampup start group: my-app_8 app (1) successor group: my-app_12 app (1) algorithm: rorb deployment id: 6ce3d626-78e7-46c8-8e32-4131c825c888 transition type: manual rampup duration: 2% of 5m test duration: 1s rampdown duration: 5m status: in_progress status messages: <none>
--- INFO: Wait result is 5
--- INFO: Rolling back update 6ce3d626-78e7-46c8-8e32-4131c825c888
Performing active-deploy-show command in org ISW / space my-space as my_email@email.com...
Showing status for deployment 6ce3d626-78e7-46c8-8e32-4131c825c888 / space 66ab12ee-1b83-4cb9-a21d-cdb3604888a9...
OK

label: my-app_8-to-my-app_12
space: my-space
routes: my-app.mybluemix.net
phase: rampup
start group: my-app_8 app (1)
successor group: my-app_12 app (1)
algorithm: rorb
deployment id: 6ce3d626-78e7-46c8-8e32-4131c825c888
transition type: manual
rampup duration: 3% of 5m
test duration: 1s
rampdown duration: 5m
status: in_progress
status messages: <none>
Performing active-deploy-rollback command in org ISW / space my-space as jagrawal@isw.net.au...
Rolling back deployment 6ce3d626-78e7-46c8-8e32-4131c825c888 / space 66ab12ee-1b83-4cb9-a21d-cdb3604888a9...
OK
label: my-app_8-to-my-app_12
space: my-space
routes: my-app.mybluemix.net
phase: rampup
start group: my-app_8 app (1)
successor group: my-app_12 app (1)
algorithm: rorb
deployment id: 6ce3d626-78e7-46c8-8e32-4131c825c888
transition type: manual
rampup duration: 4% of 5m
test duration: 1s
rampdown duration: 5m
status: rolling back
status messages: <none>
wait phase completion
--- ERROR: Unknown status: 
--- ERROR: label: my-app_8-to-my-app_12 space: my-space routes: my-app.mybluemix.net phase: rampup start group: my-app_8 app (1) successor group: my-app_12 app (1) algorithm: rorb deployment id: 6ce3d626-78e7-46c8-8e32-4131c825c888 transition type: manual rampup duration: 4% of 5m test duration: 1s rampdown duration: 5m status: rolling back status messages: <none>
--- INFO: my-app_12 stopped after rollback
--- INFO: Return code for rollback is 5
--- INFO: clean(): Current deployment (my-app_12) failed; keeping for debug purposes
--- INFO: clean(): Identified current version: my-app_8; keeping
--- INFO: clean(): Summary: keeping my-app_8 my-app_12
ERROR: Unknown status or phase encountered
--- INFO: Not deleting update 
**********************************************************************
Deployment URL
https://new-console.ng.bluemix.net/services/d615a7e6-7323-46bd-9e55-d627b2909098?ace_config={%22spaceGuid%22:%2266ab12ee-1b83-4cb9-a21d-cdb3604888a9%22}
**********************************************************************

Finished: ERRORED
```

**Comment by ptaube** [comment] 2017-04-27 15:41
This is a duplicate of https://github.com/Osthanes/update_service/issues/54

**Closed as completed by ptaube** 2017-04-27 15:41 UTC
